version: '3.3'
services:
  client:
    container_name: client_container
    build: "./client"
    restart: always
    ports:
     - "8080:3000"
    command: "npm --prefix /usr/src/app run start"
    volumes:
     - "./client:/usr/src/app"
    tty: true
  server:
    container_name: server_container
    build: "./server"
    restart: always
    ports:
     - "8888:80"
    volumes:
     - "./server:/var/www"
  database:
    container_name: database_container
    image: postgres:latest
    restart: always
    env_file:
     - "./data/database.env"
    ports:
     - "5432:5432"    
    volumes:
     - "./data/db:/var/lib/postgresql/data/"
  pg_admin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=harrybajwa@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - database   